import { env } from '~/config/environment'

//Những domain được truy cập tới tài nguyên của server
export const WHITELIST_DOMAINS = env.WHITELIST_DOMAINS ? env.WHITELIST_DOMAINS.split(',') : []

export const BOARD_TYPE = {
  PUBLIC: 'public',
  PRIVATE: 'private'
}

export const BOARD_ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER'
}

export const USER_ROLES = {
  CLIENT: 'client',
  ADMIN: 'admin'
}

export const WEBSITE_DOMAIN = env.WEBSITE_DOMAIN

export const DEFAULT_PAGE = 1
export const DEFAULT_ITEMS_PER_PAGE = 12
export const MAX_ITEMS_PER_PAGE = 100

export const INVITATION_TYPES = {
  BOARD_INVITATION: 'BOARD_INVITATION'
}
export const BOARD_INVITATION_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED'
}
export const CARD_MEMBER_ACTIONS = {
  ADD: 'ADD',
  REMOVE: 'REMOVE'
}

export const ACTIVITY_ENTITY_TYPES = {
  BOARD: 'BOARD',
  COLUMN: 'COLUMN',
  CARD: 'CARD',
  INVITATION: 'INVITATION'
}

export const ACTIVITY_ACTIONS = {
  BOARD_CREATED: 'BOARD_CREATED',
  BOARD_UPDATED: 'BOARD_UPDATED',
  BOARD_MEMBER_ROLE_CHANGED: 'BOARD_MEMBER_ROLE_CHANGED',
  COLUMN_CREATED: 'COLUMN_CREATED',
  COLUMN_UPDATED: 'COLUMN_UPDATED',
  COLUMN_DELETED: 'COLUMN_DELETED',
  CARD_CREATED: 'CARD_CREATED',
  CARD_UPDATED: 'CARD_UPDATED',
  CARD_MOVED: 'CARD_MOVED',
  CARD_COMMENTED: 'CARD_COMMENTED',
  CARD_MEMBER_ADDED: 'CARD_MEMBER_ADDED',
  CARD_MEMBER_REMOVED: 'CARD_MEMBER_REMOVED',
  INVITATION_CREATED: 'INVITATION_CREATED',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  INVITATION_REJECTED: 'INVITATION_REJECTED'
}
